apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
data:
  config.yml: |-
    global:
      resolve_timeout: 1m
      slack_api_url: 'https://hooks.slack.com/services/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'
    
    route:
      receiver: slack-notifications
      group_interval: 30s
      repeat_interval: 30s

    receivers:
      - name: 'slack-notifications'
       slack_configs:
        - channel: '#monitoring-instances'
          send_resolved: true
