apiVersion: v1
kind: Service
metadata:
  name: rabbit-prom-service
spec:
  selector: 
    app: rabbitmq
    release: mu-rabbit
  type: LoadBalancer  
  ports:
    - port: 15692
      targetPort: 15692 
